# Generated by Django 2.1.1 on 2018-09-05 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core', models.CharField(default='3', max_length=2)),
                ('model_vendor', models.CharField(choices=[('I3', 'Intel Core I3'), ('I5', 'Intel Core I5'), ('I7', 'Intel Core I7'), ('E7', 'AMD EPYC 7551')], default='I3', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.CharField(choices=[('HD', 'HD 120GB'), ('SSD', 'SSD 120GB')], default='HD', max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='notebook',
            name='ram',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notebooks.Ram'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='vendor',
            field=models.CharField(choices=[('HP', 'Hewlett Packard'), ('DELL', 'Dell Corporation'), ('SAMSUNG', 'Samsung Corporation'), ('AVELL', 'High Performance')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='notebook',
            name='cpu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notebooks.CPU'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notebooks.Storage'),
        ),
    ]
